version: '3.6'
services:
  backup:
    restart: always
    build: ./recipes/backup
    image: k0gihf9s/backup:1.00
    volumes:
      - ./data/other/backups:/var/backup
      - ./data/jenkins/jenkins:/var/target/monthly/jenkins
      - ./data/gitlab/gitlab/shared/lfs-objects:/var/target/monthly/gitlab/lfs-objects
      - ./data/gitlab/gitlab/.ssh:/var/target/monthly/gitlab/.ssh
      - gitlab-ssh-volume:/var/target/monthly/gitlab/ssh
    environment:
      - TZ=Asia/Tokyo

  privileged:
    restart: always
    image: busybox:1.28.4
    privileged: true
    command: >
      sh -c
      "echo never | tee /sys/kernel/mm/transparent_hugepage/enabled;
      echo never | tee /sys/kernel/mm/transparent_hugepage/defrag;
      while true; do sleep 10000d; done;"

  gitlab-mysql:
    restart: always
    image: mysql:5.7.22
    volumes:
      - ./data/gitlab/mysql:/var/lib/mysql
      - ./recipes/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      - TZ=Asia/Tokyo

      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=gitlab
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=gitlabhq_production

  gitlab-redis:
    restart: always
    image: redis:4.0.9-alpine
    command:
      - --loglevel warning
    depends_on:
      - privileged
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - ./data/gitlab/redis:/data
    environment:
      - TZ=Asia/Tokyo

  gitlab-ci-multi-runner:
    restart: always
    build: recipes/gitlab-ci-multi-runner
    image: k0gihf9s/gitlab-ci-multi-runner:1.00
    depends_on:
      - gitlab
    volumes:
      - ./data/gitlab/gitlab-ci-multi-runner:/home/gitlab_ci_multi_runner/data
    environment:
      - TZ=Asia/Tokyo

      - CI_SERVER_URL=http://gitlab/gitlab/ci
      - RUNNER_TOKEN=XvhgTk3ecqp1Vt1aoh1B
      - RUNNER_DESCRIPTION=runner1
      - RUNNER_EXECUTOR=shell

  gitlab:
    restart: always
    build: recipes/gitlab
    image: k0gihf9s/gitlab:11.3.4
    depends_on:
      - gitlab-redis
      - gitlab-mysql
      - redmine
    volumes:
      - ./data/gitlab/gitlab/backups:/home/git/data/backups
      - ./data/gitlab/gitlab/builds:/home/git/data/builds
      - ./data/gitlab/gitlab/repositories:/home/git/data/repositories
      - ./data/gitlab/gitlab/shared/lfs-objects:/home/git/data/shared/lfs-objects
      - ./data/gitlab/gitlab/tmp:/home/git/data/tmp
      - ./data/gitlab/gitlab/uploads:/home/git/data/uploads
      - ./data/gitlab/gitlab/.ssh:/home/git/data/.ssh
      - gitlab-ssh-volume:/home/git/data/ssh
      - gitlab-artifacts-volume:/home/git/data/shared/artifacts
      - gitlab-pages-volume:/home/git/data/shared/pages
    environment:
      - DEBUG=false
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - DB_ADAPTER=mysql2
      - DB_HOST=gitlab-mysql
      - DB_PORT=3306
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_SECRETS_DB_KEY_BASE=crbWbKhtCcnsjFMwPz7RFqrjbgWPjkzgwrnt9hL3KPwsjnhMVp37dKjTzvJHmzTk
      - GITLAB_SECRETS_SECRET_KEY_BASE=Fpg3dxXqcWwMtzTrJFVCfFkcspJsr9NH9MqjmsqgcRxTJ7VC4r7CwjsmwstVcWLC
      - GITLAB_SECRETS_OTP_KEY_BASE=RcgRF3NpcFtXXHgbmqTzL3RL3PWNczqKpXX73CRJgTnCmsbfftzvMKrjVz3z3qsb

      - GITLAB_HOST=hswinter.mydns.jp
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=/gitlab

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00
      - GITLAB_BACKUP_EXPIRY=604800
      - GITLAB_BACKUP_SKIP=lfs

      - SMTP_ENABLED=true
      - SMTP_USER=gitlab@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_DOMAIN=hswinter.mydns.jp
      - GITLAB_PAGES_HTTPS=false
      - GITLAB_PAGES_PORT=80
      - GITLAB_PAGES_EXTERNAL_HTTP=:8010

      - OAUTH_ENABLED=true
      - OAUTH_ALLOW_SSO=redmine
      - OAUTH_BLOCK_AUTO_CREATED_USERS=false
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false

      - OAUTH_REDMINE_API_KEY=qrVKexnOqa2IL0oee50kCBUDBcqL1nOwpQXGpt4L
      - OAUTH_REDMINE_API_SECRET=7n3jbUDlqqJoOnwEKEU2sfMIWOZlkEG8wRuTyw4v
      - OAUTH_REDMINE_DOMAIN=http://hswinter.mydns.jp/redmine

  redmine-mysql:
    restart: always
    image: mysql:5.7.22
    environment:
      - TZ=Asia/Tokyo

      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
    volumes:
      - ./data/redmine/mysql:/var/lib/mysql
      - ./recipes/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  redmine-memcached:
    restart: always
    image: memcached:1.5.8-alpine
    environment:
      - TZ=Asia/Tokyo

  redmine:
    restart: always
    build: recipes/redmine
    image: k0gihf9s/redmine:3.4.6
    depends_on:
      - redmine-mysql
      - redmine-memcached
    volumes:
      - ./data/redmine/redmine:/home/redmine/data
      - ./data/gitlab/gitlab/repositories:/git
    environment:
      - TZ=Asia/Tokyo

      - DB_ADAPTER=mysql2
      - DB_HOST=redmine-mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - MEMCACHE_HOST=redmine-memcached
      - MEMCACHE_PORT=11211

      - REDMINE_PORT=80
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=AtbntKzzO8vUjVwSnt9Cb7tDDkbM6UsUuSc5O7EATRBeqMyL7Gk0p14lwqGod

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800
      - REDMINE_BACKUP_TIME=1:00

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_USER=redmine@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

  jenkins:
    restart: always
    build: recipes/jenkins
    image: k0gihf9s/jenkins:1.9.0
    depends_on:
      - redmine-mysql
    environment:
      - TZ=Asia/Tokyo

      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
    volumes:
      - ./data/jenkins/jenkins:/var/jenkins_home

  mattermost:
    restart: always
    build: recipes/mattermost
    image: k0gihf9s/mattermost:5.5.1
    volumes:
      - ./data/mattermost/mattermost/config:/mattermost/config
      - ./data/mattermost/mattermost/data:/mattermost/data
      - ./data/mattermost/mattermost/logs:/mattermost/logs
      - ./data/mattermost/mattermost/plugins:/mattermost/plugins
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - DB_HOST=mattermost-mysql
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(mattermost-mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - TZ=Asia/Tokyo

  mattermost-mysql:
    restart: always
    image: mysql:5.7.22
    environment:
      - TZ=Asia/Tokyo

      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost
    volumes:
      - ./data/mattermost/mysql:/var/lib/mysql
      - ./recipes/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  ldap:
    image: osixia/openldap-backup:1.2.1
    volumes:
      - ./data/ldap/backup:/data/backup
      - ldap-data-volume:/var/lib/ldap
      - ldap-config-volume:/etc/ldap/slapd.d
    environment:
      - TZ=Asia/Tokyo

      - LDAP_ORGANISATION=k0gihf9s
      - LDAP_DOMAIN=hswinter.mydns.jp
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config

      - LDAP_BACKUP_CONFIG_CRON_EXP=0 4 1 * *
      - LDAP_BACKUP_DATA_CRON_EXP=0 4 1 * *z
      - LDAP_BACKUP_TTL=15

  phpldapadmin:
    image: osixia/phpldapadmin:0.7.1
    depends_on:
      - ldap
    environment:
      - TZ=Asia/Tokyo

      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false

  nginx:
    restart: always
    image: nginx:1.14.0-alpine
    ports:
      - '80:80'
      - '22:22'
      - '50000:50000'
    volumes:
      - ./recipes/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./recipes/nginx/html:/usr/share/nginx/html:ro
    environment:
      - TZ=Asia/Tokyo

volumes:
  gitlab-ssh-volume:
  gitlab-artifacts-volume:
  gitlab-pages-volume:
  ldap-data-volume:
  ldap-config-volume: