services:
  privileged:
    restart: on-failure
    image: busybox:1.30.1
    privileged: true
    command: >
      sh -c
      "echo never | tee /sys/kernel/mm/transparent_hugepage/enabled;
      echo never | tee /sys/kernel/mm/transparent_hugepage/defrag;
      sysctl -w vm.max_map_count=262144;
      sysctl -w fs.file-max=65536;
      ulimit -n 65536;
      ulimit -u 4096;
      while true; do sleep 10000d; done;"

  gitlab-postgres:
    restart: on-failure
    image: postgres:${GITLAB_POSTGRES_TAG}
    healthcheck:
      test: "pg_isready -U gitlab"
      interval: 1m
      timeout: 5s
      retries: 5
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitlabhq_production
    volumes:
      - ./data/gitlab/postgresql/15/data:/var/lib/postgresql/data
  gitlab-redis:
    restart: on-failure
    image: redis:${GITLAB_REDIS_TAG}
    healthcheck:
      test: "redis-cli ping"
      interval: 1m
      timeout: 5s
      retries: 5
    command:
      - --loglevel warning
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - ./data/gitlab/redis:/data
    environment:
      - TZ=Asia/Tokyo
  gitlab:
    restart: on-failure
    image: k0gihf9s/gitlab:${GITLAB_TAG}
    build:
      context: ./recipes/gitlab
      args:
        GITLAB_TAG: ${GITLAB_TAG}
    depends_on:
      - gitlab-postgres
      - gitlab-redis
    healthcheck:
      test: "healthcheck"
      interval: 1m
      timeout: 5s
      retries: 5
      start_period: 2m
    volumes:
      - ./backup/gitlab:/backups
      - ./data/gitlab/gitlab/repositories:/repositories
      - ./data/gitlab/gitlab/lfs-objects:/lfs
      - ./data/gitlab/gitlab/data:/home/git/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEBUG=false
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_REPOS_DIR=/repositories
      - GITLAB_BACKUP_DIR=/backups
      - GITLAB_LFS_OBJECTS_DIR=/lfs

      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgres
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=false

      - GITLAB_SECRETS_DB_KEY_BASE=crbWbKhtCcnsjFMwPz7RFqrjbgWPjkzgwrnt9hL3KPwsjnhMVp37dKjTzvJHmzTk
      - GITLAB_SECRETS_SECRET_KEY_BASE=Fpg3dxXqcWwMtzTrJFVCfFkcspJsr9NH9MqjmsqgcRxTJ7VC4r7CwjsmwstVcWLC
      - GITLAB_SECRETS_OTP_KEY_BASE=RcgRF3NpcFtXXHgbmqTzL3RL3PWNczqKpXX73CRJgTnCmsbfftzvMKrjVz3z3qsb

      - GITLAB_HOST=${SERVER_NAME}
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=/gitlab

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00
      - GITLAB_BACKUP_EXPIRY=604800
      - GITLAB_BACKUP_SKIP=lfs

      - SMTP_ENABLED=true
      - SMTP_USER=gitlab@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_DOMAIN=${SERVER_NAME}
      - GITLAB_PAGES_HTTPS=true
      - GITLAB_PAGES_PORT=443
      - GITLAB_PAGES_EXTERNAL_HTTP=:8050
      - GITLAB_PAGES_NGINX_PROXY=false

      - GITLAB_PAGES_ACCESS_CONTROL=true
      - GITLAB_PAGES_ACCESS_CONTROL_SERVER=https://${SERVER_NAME}/gitlab
      - GITLAB_PAGES_ACCESS_CLIENT_ID=63ca5b0ce83517d99a10168b48fec303d3a1bdeb52d1c9d591e421b4c19ec4ed
      - GITLAB_PAGES_ACCESS_CLIENT_SECRET=33a522185269699bb9294148dd6b928f4c36de288773bd471bb00383610a5d80
      - GITLAB_PAGES_ACCESS_REDIRECT_URI=https://projects.${SERVER_NAME}/auth

      - OAUTH_ENABLED=true
      - OAUTH_ALLOW_SSO=redmine
      - OAUTH_BLOCK_AUTO_CREATED_USERS=false
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false

      - OAUTH_REDMINE_API_KEY=iVCawArsgFDWcuGj1z7nN0oN8wlb9rFpjlFsz8Gg
      - OAUTH_REDMINE_API_SECRET=bNZqnXumJKoCvkc7tdpUTg4nUoROtBczjxAPC9tP
      - OAUTH_REDMINE_DOMAIN=https://${SERVER_NAME}/redmine

      - NGINX_REAL_IP_RECURSIVE=on
      - NGINX_REAL_IP_TRUSTED_ADDRESSES=172.18.0.0/16
    networks:
      default:
      front:
        ipv4_address: 192.168.231.3

  kroki:
    image: yuzutech/kroki
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    networks:
      default:
      front:
        ipv4_address: 192.168.231.14
  blockdiag:
    image: yuzutech/kroki-blockdiag
  mermaid:
    image: yuzutech/kroki-mermaid
  bpmn:
    image: yuzutech/kroki-bpmn
  excalidraw:
    image: yuzutech/kroki-excalidraw

  redmine-mysql:
    restart: on-failure
    image: k0gihf9s/mysql:${REDMINE_MYSQL_TAG}
    build:
      context: ./recipes/mysql
      args:
        REDMINE_MYSQL_TAG: ${REDMINE_MYSQL_TAG}
    healthcheck:
      test: "mysqladmin ping -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 1m
      timeout: 5s
      retries: 5
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
    volumes:
      - ./data/redmine/mysql:/var/lib/mysql
  redmine-memcached:
    restart: on-failure
    image: memcached:${REDMINE_MEMCACHED_TAG}
    command: -v
    healthcheck:
      test: "nc -z -w 1 localhost 11211"
      interval: 1m
      timeout: 5s
      retries: 5
    environment:
      - TZ=Asia/Tokyo
  chupa-text:
    image: groonga/chupa-text:${CHUPA_TEXT_TAG}
    environment:
      TZ: Asia/Tokyo
      RAILS_SERVE_STATIC_FILES: "true"
      CHUPA_TEXT_EXTERNAL_COMMAND_LIMIT_CPU: 5
      CHUPA_TEXT_EXTERNAL_COMMAND_LIMIT_AS: 2GB
      CHUPA_TEXT_EXTERNAL_COMMAND_TIMEOUT: 10
      CHUPA_TEXT_DECOMPOSER_WEBKIT_TIMEOUT: 10
    volumes:
      - ./logs/redmine/chupa-text:/home/chupa-text/chupa-text-http-server/log:z
  redmine:
    restart: on-failure
    image: k0gihf9s/redmine:${REDMINE_TAG}
    build:
      context: ./recipes/redmine
      args:
        REDMINE_TAG: ${REDMINE_TAG}
    depends_on:
      - redmine-mysql
      - redmine-memcached
      - chupa-text
    volumes:
      - ./backup/redmine:/backups
      - ./data/redmine/redmine:/home/redmine/data
      - ./data/gitlab/gitlab/repositories:/git
    environment:
      - TZ=Asia/Tokyo

      - DB_ADAPTER=mysql2
      - DB_HOST=redmine-mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - DB_ENCODING=utf8mb4

      - MEMCACHE_HOST=redmine-memcached
      - MEMCACHE_PORT=11211

      - REDMINE_PORT=443
      - REDMINE_HTTPS=true
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=AtbntKzzO8vUjVwSnt9Cb7tDDkbM6UsUuSc5O7EATRBeqMyL7Gk0p14lwqGod

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUPS_DIR=/backups
      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800
      - REDMINE_BACKUP_TIME=1:00

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_USER=redmine@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

      - REDMINE_MINIMAGICK_FONT_PATH=/usr/share/fonts/opentype/ipafont-gothic/ipagp.ttf

      - NGINX_REAL_IP_RECURSIVE=on
      - NGINX_REAL_IP_TRUSTED_ADDRESSES=172.18.0.0/16
    networks:
      default:
      front:
        ipv4_address: 192.168.231.4

  sonarqube-postgres:
    restart: on-failure
    image: postgres:${SONARQUBE_POSTGRES_TAG}
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube_password
      - POSTGRES_DB=sonarqube
    volumes:
      - ./data/sonarqube/postgres13:/var/lib/postgresql/data
  sonarqube:
    restart: on-failure
    image: sonarqube:${SONARQUBE_TAG}
    depends_on:
      - sonarqube-postgres
    volumes:
      - ./data/sonarqube/sonarqube/config:/opt/sonarqube/conf
      - ./data/sonarqube/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/sonarqube/plugins:/opt/sonarqube/extensions
      - ./logs/sonarqube:/opt/sonarqube/logs
    environment:
      - TZ=Asia/Tokyo
      - sonar.jdbc.username=sonarqube
      - sonar.jdbc.password=sonarqube_password
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgres:5432/sonarqube?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - SONAR_WEB_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-${SONARQUBE_BRANCH_PLUGIN_VERSION}.jar=web
      - SONAR_CE_JAVAADDITIONALOPTS=-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-${SONARQUBE_BRANCH_PLUGIN_VERSION}.jar=ce
    command: >
      -Dsonar.web.context=/sonarqube
      -Dsonar.web.port=9000
    networks:
      default:
      front:
        ipv4_address: 192.168.231.6

  nginx:
    restart: on-failure
    image: nginx:${NGINX_TAG}
    mem_limit: 128m
    ports:
      - "65124:80"
      - "22:22"
    volumes:
      - ./recipes/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./recipes/nginx/etc/my.conf.d:/etc/nginx/my.conf.d:ro
      - ./recipes/nginx/html:/usr/share/nginx/html:ro
    environment:
      - TZ=Asia/Tokyo
    networks:
      front:
        ipv4_address: 192.168.231.2

networks:
  front:
    ipam:
      driver: default
      config:
        - subnet: 192.168.231.0/24
    name: front
