version: '3.6'
services:
  privileged:
    restart: always
    image: busybox:1.30.1
    privileged: true
    command: >
      sh -c
      "echo never | tee /sys/kernel/mm/transparent_hugepage/enabled;
      echo never | tee /sys/kernel/mm/transparent_hugepage/defrag;
      while true; do sleep 10000d; done;"

  gitlab-postgres:
    restart: always
    image: postgres:12.3-alpine
    environment:
      - TZ=Asia/Tokyo

      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gitlabhq_production

    volumes:
      - gitlab-postgres-volume-12:/var/lib/postgresql/data
  gitlab-redis:
    restart: always
    image: redis:5.0.7-alpine
    command:
      - --loglevel warning
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - ./data/gitlab/redis:/data
    environment:
      - TZ=Asia/Tokyo
  gitlab-ci-multi-runner:
    restart: always
    image: gitlab/gitlab-runner:alpine-v13.1.3
    volumes:
      - ./data/gitlab/gitlab-ci-multi-runner/data:/home/gitlab-runner
      - ./data/gitlab/gitlab-ci-multi-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Asia/Tokyo

      - REGISTER_NON_INTERACTIVE=true
      - CI_SERVER_URL=http://192.168.11.7/gitlab/
      - REGISTRATION_TOKEN=dsojDECUB8jeXaZzY4Gp
      - RUNNER_NAME=runner1
      - RUNNER_EXECUTOR=docker
      - RUNNER_TAG_LIST=docker
      - RUNNER_LIMIT=1
      - DOCKER_IMAGE=alpine:latest
      - DOCKER_VOLUMES=/var/run/docker.sock:/var/run/docker.sock
  gitlab:
    restart: always
    build: recipes/gitlab
    image: k0gihf9s/gitlab:13.3.4
    volumes:
      - ./data/gitlab/gitlab/backups:/backups
      - ./data/gitlab/gitlab/repositories:/repositories
      - ./data/gitlab/gitlab/lfs-objects:/lfs
      - gitlab-data-volume:/home/git/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEBUG=false
      - TZ=Asia/Tokyo
      - GITLAB_TIMEZONE=Tokyo

      - GITLAB_REPOS_DIR=/repositories
      - GITLAB_BACKUP_DIR=/backups
      - GITLAB_LFS_OBJECTS_DIR=/lfs

      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgres
      - DB_PORT=5432
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production

      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379

      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false

      - GITLAB_SECRETS_DB_KEY_BASE=crbWbKhtCcnsjFMwPz7RFqrjbgWPjkzgwrnt9hL3KPwsjnhMVp37dKjTzvJHmzTk
      - GITLAB_SECRETS_SECRET_KEY_BASE=Fpg3dxXqcWwMtzTrJFVCfFkcspJsr9NH9MqjmsqgcRxTJ7VC4r7CwjsmwstVcWLC
      - GITLAB_SECRETS_OTP_KEY_BASE=RcgRF3NpcFtXXHgbmqTzL3RL3PWNczqKpXX73CRJgTnCmsbfftzvMKrjVz3z3qsb

      - GITLAB_HOST=192.168.11.7
      - GITLAB_PORT=80
      - GITLAB_SSH_PORT=22
      - GITLAB_RELATIVE_URL_ROOT=/gitlab

      - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      - GITLAB_NOTIFY_PUSHER=false

      - GITLAB_EMAIL=notifications@example.com
      - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00
      - GITLAB_BACKUP_EXPIRY=604800
      - GITLAB_BACKUP_SKIP=lfs

      - SMTP_ENABLED=true
      - SMTP_USER=gitlab@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false

      - GITLAB_PAGES_ENABLED=true
      - GITLAB_PAGES_DOMAIN=hswinter.mydns.jp
      - GITLAB_PAGES_HTTPS=false
      - GITLAB_PAGES_PORT=80
      - GITLAB_PAGES_EXTERNAL_HTTP=:8010

      - OAUTH_ENABLED=true
      - OAUTH_ALLOW_SSO=redmine
      - OAUTH_BLOCK_AUTO_CREATED_USERS=false
      - OAUTH_AUTO_LINK_LDAP_USER=false
      - OAUTH_AUTO_LINK_SAML_USER=false

      - GITLAB_MATTERMOST_ENABLED=true
      - GITLAB_MATTERMOST_URL=http://192.168.11.7/mattermost

      - OAUTH_REDMINE_API_KEY=qrVKexnOqa2IL0oee50kCBUDBcqL1nOwpQXGpt4L
      - OAUTH_REDMINE_API_SECRET=7n3jbUDlqqJoOnwEKEU2sfMIWOZlkEG8wRuTyw4v
      - OAUTH_REDMINE_DOMAIN=http://192.168.11.7/redmine

      - NGINX_REAL_IP_RECURSIVE=on
      - NGINX_REAL_IP_TRUSTED_ADDRESSES=172.18.0.0/16

  redmine-mysql:
    restart: always
    build: recipes/mysql
    image: k0gihf9s/mysql:5.7.29
    environment:
      - TZ=Asia/Tokyo

      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=redmine
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=redmine_production
    volumes:
      - ./data/redmine/mysql:/var/lib/mysql
  redmine-memcached:
    restart: always
    image: memcached:1.5.21-alpine
    environment:
      - TZ=Asia/Tokyo
  redmine:
    restart: always
    build: recipes/redmine
    image: k0gihf9s/redmine:4.1.1-6
    volumes:
      - ./data/redmine/redmine:/home/redmine/data
      - ./data/gitlab/gitlab/repositories:/git
    environment:
      - TZ=Asia/Tokyo

      - DB_ADAPTER=mysql2
      - DB_HOST=redmine-mysql
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production

      - MEMCACHE_HOST=redmine-memcached
      - MEMCACHE_PORT=11211

      - REDMINE_PORT=80
      - REDMINE_HTTPS=false
      - REDMINE_RELATIVE_URL_ROOT=/redmine
      - REDMINE_SECRET_TOKEN=AtbntKzzO8vUjVwSnt9Cb7tDDkbM6UsUuSc5O7EATRBeqMyL7Gk0p14lwqGod

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - REDMINE_BACKUP_SCHEDULE=daily
      - REDMINE_BACKUP_EXPIRY=604800
      - REDMINE_BACKUP_TIME=1:00

      - SMTP_ENABLED=true
      - SMTP_METHOD=smtp
      - SMTP_USER=redmine@k0gihf9s.com
      - SMTP_PASS=password
      - SMTP_DOMAIN=smtp.gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_INTERVAL=30

      - NGINX_REAL_IP_RECURSIVE=on
      - NGINX_REAL_IP_TRUSTED_ADDRESSES=172.18.0.0/16

  jenkins:
    restart: always
    build: recipes/jenkins
    image: k0gihf9s/jenkins:1.23.2
    environment:
      - TZ=Asia/Tokyo

      - JENKINS_OPTS=--prefix=/jenkins --sessionTimeout=0
      - JAVA_OPTS=-Duser.timezone=Asia/Tokyo -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
    volumes:
      - ./data/jenkins/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mattermost:
    restart: always
    build: recipes/mattermost
    image: k0gihf9s/mattermost:5.19.0
    volumes:
      - ./data/mattermost/mattermost/config:/mattermost/config
      - ./data/mattermost/mattermost/data:/mattermost/data
      - ./data/mattermost/mattermost/logs:/mattermost/logs
      - ./data/mattermost/mattermost/plugins:/mattermost/plugins
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      - DB_HOST=mattermost-mysql
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=mmuser:mmuser_password@tcp(mattermost-mysql:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - TZ=Asia/Tokyo
  mattermost-mysql:
    restart: always
    image: mysql:5.7.29
    environment:
      - TZ=Asia/Tokyo

      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mmuser_password
      - MYSQL_DATABASE=mattermost
    volumes:
      - ./data/mattermost/mysql:/var/lib/mysql
      - ./recipes/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  ldap:
    image: osixia/openldap-backup:1.3.0
    volumes:
      - ./data/ldap/backup:/data/backup
      - ldap-data-volume:/var/lib/ldap
      - ldap-config-volume:/etc/ldap/slapd.d
    environment:
      - TZ=Asia/Tokyo

      - LDAP_ORGANISATION=k0gihf9s
      - LDAP_DOMAIN=hswinter.mydns.jp
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=config

      - LDAP_BACKUP_CONFIG_CRON_EXP=0 4 1 * *
      - LDAP_BACKUP_DATA_CRON_EXP=0 4 1 * *z
      - LDAP_BACKUP_TTL=15
  phpldapadmin:
    build: recipes/phpldapadmin
    image: k0gihf9s/phpldapadmin:0.9.0
    depends_on:
      - ldap
    environment:
      - TZ=Asia/Tokyo

      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false

  sonarqube:
    restart: always
    image: sonarqube:7.9-community
    volumes:
      - ./data/sonarqube/sonarqube/config:/opt/sonarqube/conf
      - ./data/sonarqube/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/sonarqube/logs:/opt/sonarqube/logs
      - ./data/sonarqube/sonarqube/plugins:/opt/sonarqube/extensions
    environment:
      - sonar.jdbc.username=sonarqube
      - sonar.jdbc.password=sonarqube_password
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgres:5432/sonarqube?useUnicode=true&characterEncoding=utf8&useSSL=false&rewriteBatchedStatements=true
      - TZ=Asia/Tokyo
    command: >
      -Dsonar.web.context=/sonarqube
      -Dsonar.web.port=9000

  sonarqube-postgres:
    restart: always
    image: postgres:11.6-alpine
    environment:
      - TZ=Asia/Tokyo

      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube_password
      - POSTGRES_DB=sonarqube
    volumes:
      - sonarqube-postgres-volume:/var/lib/postgresql/data

  keycloak:
    restart: always
    build: recipes/keycloak
    image: k0gihf9s/keycloak:11.0.0
    environment:
      - TZ=Asia/Tokyo

      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=M0I6U2WVU8KFSlGqf0Ob
      - PROXY_ADDRESS_FORWARDING=true
      - JDBC_PARAMS=useSSL=false
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak_password

  keycloak-postgres:
    restart: always
    image: postgres:11.6-alpine
    environment:
      - TZ=Asia/Tokyo

      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-postgres-volume:/var/lib/postgresql/data

  es01:
    restart: always
    build: recipes/elasticsearch
    image: k0gihf9s/elasticsearch:7.5.2
    environment:
      - TZ=Asia/Tokyo
      # - discovery.type=single-node
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/backup"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es01-volume:/usr/share/elasticsearch/data
      - ./data/elasticsearch/backup:/usr/share/elasticsearch/backup
      # - ./recipes/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  es02:
    restart: always
    build: recipes/elasticsearch
    image: k0gihf9s/elasticsearch:7.5.2
    environment:
      - TZ=Asia/Tokyo
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "path.repo=/usr/share/elasticsearch/backup"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es02-volume:/usr/share/elasticsearch/data
      - ./data/elasticsearch/backup:/usr/share/elasticsearch/backup
      # - ./recipes/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  logstash:
    restart: always
    build: recipes/logstash
    image: k0gihf9s/logstash:7.5.2
    volumes:
      - ./recipes/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - TZ=Asia/Tokyo
  kibana:
    restart: always
    build: recipes/kibana
    image: k0gihf9s/kibana:7.5.2
    volumes:
      - ./recipes/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - TZ=Asia/Tokyo
      - I18N_LOCALE="ja-JP"

  testlink-mariadb:
    restart: always
    image: bitnami/mariadb:10.2.31
    environment:
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/testlink/mariadb:/bitnami/mariadb
  testlink:
    restart: always
    build: recipes/testlink
    image: k0gihf9s/testlink:1.9.20
    environment:
      - TZ=Asia/Tokyo
      - TESTLINK_LANGUAGE=ja_JP
      - MARIADB_HOST=testlink-mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/testlink/testlink:/bitnami/testlink

  nginx:
    restart: always
    image: nginx:1.17.8-alpine
    ports:
      - '8080:80'
      - '2222:22'
      - '60000:60500'
    volumes:
      - ./recipes/nginx/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./recipes/nginx/html:/usr/share/nginx/html:ro
    environment:
      - TZ=Asia/Tokyo

volumes:
  gitlab-data-volume:
  gitlab-postgres-volume-12:
  ldap-data-volume:
  ldap-config-volume:
  sonarqube-postgres-volume:
  keycloak-postgres-volume:
  es01-volume:
  es02-volume:
